site_name: MP14 ASSEMBLY GUIDE

extra_css:
  - stylesheets/extra.css

extra:
  generator: false

markdown_extensions:
  - attr_list
  - md_in_html

theme:
  name: material
  logo:
  features:
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.expand
    - navigation.tracking
    - toc.integrate
    - navigation.instant
  palette:
    primary: white

plugins: []

nav:
  - "index.md"
  - Parts and Materials: "parts_and_materials/pm.md"
  - Safety: "safety/safe.md"
  - Printed Circuit Board:
      - "pcb/index.md"
      - Adafruit Trinket M0: "pcb/trinket.md"
      - Tactile Switch: "pcb/tactile.md"
      - Potentiometer: "pcb/pot.md"
      - 555 Timer: "pcb/555.md"
      - Resistors & Capacitors: "pcb/rescap.md"
      - TRS: "pcb/trs.md"
      - Copper Probes: "pcb/probe.md"
      - Power and Ground (Optional): "pcb/pg.md"
  - MP14 Firmware Setup Guide: "firmware/firm.md"
  - 3D Printed Components:
      - "3d_components/index.md"
      - PCB Bracket: "3d_components/brac.md"
      - Planter: "3d_components/plant.md"
      - Shell: "3d_components/shell.md"
      - Hood: "3d_components/hood.md"
      - Button & Knob: "3d_components/buk.md"
      - Pool: "3d_components/pool.md"
  - Assembly: "assembly_components/index.md"
